AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  awc-rc

  Sample SAM Template for awc-rc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
    S3bucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: aws-rc-cloud
       AccessControl: PublicRead
       WebsiteConfiguration:
         IndexDocument: index.html

    bucketpolicy:
     Type: AWS::S3::BucketPolicy
     Properties:
       Bucket: !Ref S3bucket
       PolicyDocument:
         Id: aws-clou-rc
         Vesion: 2012-10-17
         Statement:
         - Sid: PublicReadForGetBucketObjects
           Effect: Allow
           Action: "s3:GetObject"
           Resource: !Join 
           - ""
           - - "arn:aws:s3:::"
             - !Ref S3bucket
             - /*
         
         

