name: "Aws_Frontend_git_Action"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tfpath:
        description: 'TF FILE Path'
        required: false
        default: 'Front_end_Automation'
env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
    build-infra:
      runs-on: ubuntu-latest
      timeout-minutes: 2

      steps:
         - uses: actions/checkout@v2.5.0

         - name: Configure AWS Credentials Action For GitHub Actions
           uses: aws-actions/configure-aws-credentials@v1
           with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION}}

         -  name: Setup Terraform CLI
            uses: hashicorp/setup-terraform@v2.0.2

         -  name: terraform Init,plan and apply
            run: |
              cd Front_end_Automation
              echo `pwd`
              echo "tfpath ${{ github.event.inputs.tfpath }}"
              echo "** Running Terraform Init**"
              terraform init

              echo "** Running Terraform Format**"
              terraform fmt

              echo "** Running Terraform Validate**"
              terraform validate

              echo "** Running Terraform Plan**"
              terraform plan

              echo "** Runnning Terraform Apply**"
              terraform apply -auto-approve
            working-directory: ${{github.event.inputs.tfpath}}
         -  name: Terraform Destroy
            run: |
              echo "** Running Terraform Destroy**"
              terraform plan -destroy
      #        terraform destroy -auto-approve
            working-directory: ${{ github.event.inputs.tfpath }}
    deploy-site:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: jakejarvis/s3-sync-action@master
          with:
            args: --delete
          env:
            AWS_S3_BUCKET: aws-rc-cloud
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            SOURCE_DIR: Website
