name: main
on: push

jobs:
    build-infra:
      runs-on: ubuntu-latest
      timeout-minutes: 2
      steps: 
         - uses: actions/checkout@v2
         - uses: actions/setup-pyhton@v2
         - uses: aws-actions/seups-sam@1
         - uses: 
